moved asterisk to beginning of label and added an aria-Label =require…
gcxchange-gcechange/spfx-scw pull request #34
Opened 2023-07-19 19:21 UTC by gabmor38

…d to them

2023-07-20 17:09 UTC, Steph4104 requested changes
Translation is missing

required field in English and in French: champ obligatoire

2023-07-21 01:22 UTC, gabmor38 commented
I have changed the aria-Label to be bilingual

2023-07-21 11:51 UTC, Steph4104 requested changes

2023-07-21 11:51 UTC, Steph4104 commented on src/webparts/scw/loc/en-us.js
> +    'required': 'required',
the world field is missing. Need to be"required field"

2023-07-24 12:55 UTC, Steph4104 approved these changes

2023-07-24 14:30 UTC, merged